# pull official base image
FROM node:14.16.0

# create user group `app` and system user `app` to `app` group
RUN addgroup app && adduser --system --group app
#create app folder and change app folder permission group to `app:app`
RUN mkdir /app && chown app:app /app
#switch user from `root` to `user`
USER app

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm install

# add app
COPY . .

# show port is 3000
EXPOSE 3000

# start app
CMD [ "npm", "start" ]

