/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a2ef661b-ece7-4b57-9434-96bbe6468986",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_PuhG2hm8W",
    "aws_user_pools_web_client_id": "451oqo0irumiij3qkhr95nnd35",
    "oauth": {
        "domain": "uwcssats-devts.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://devts.uwcssa.ca/,https://production.uwcssa.ca/,https://uwcssa.ca/",
        "redirectSignOut": "http://localhost:3000/,https://devts.uwcssa.ca/,https://production.uwcssa.ca/,https://uwcssa.ca/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "uwcssats225941-devts",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://sd6ft0jw79.execute-api.us-east-2.amazonaws.com/devts",
            "region": "us-east-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://a6pcmcs2sze5rd5x7vbuzhtz24.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
