# Generated by Django 3.2.5 on 2021-07-27 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='news',
            name='subject',
        ),
        migrations.AddField(
            model_name='news',
            name='s',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.topic'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
