# Generated by Django 3.2.5 on 2021-07-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210727_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='s',
            new_name='t',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='subject',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='news',
            name='subject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
