# Generated by Django 3.2.6 on 2021-08-07 16:01

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_topic_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=news.models.upload_to),
        ),
    ]
