# Generated by Django 3.2.6 on 2021-08-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='starter',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='last_updated',
        ),
    ]
