# Generated by Django 3.2.5 on 2021-07-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210727_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
