# Generated by Django 3.2.5 on 2021-07-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_topic_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
    ]
