# Generated by Django 3.2.5 on 2021-07-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_topic_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='t',
            new_name='topic',
        ),
    ]
